
name: Checking clean build of the downstream linux tree

on:
  push:
    paths: 
      - "linux"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: download and unzip
        run: 
          wget https://github.com/citade1/linux/archive/$(git rev-parse @:./linux).zip
          unzip $(git rev-parse @:./linux).zip
      
      - name: build 
        shell: bash
        run: |
          ./install-deps.sh
          ./build-linux.sh ./linux-$(git rev-parse @:./linux) tinyconfig
