
name: Checking clean build of the downstream linux tree

on:
  push:
    paths: 
      - "linux"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: download and unzip the linux repository 
        run: 
          wget https://github.com/citade1/linux/archive/linux-$(git rev-parse @:./linux).zip
          unzip linux-$(git rev-parse @:./linux).zip
      
      - name: build the downloaded linux repoistory
        shell: bash
        run: |
          ./install-deps.sh
          ./build-linux.sh linux-$(git rev-parse @:./linux) tinyconfig
