# This is a basic workflow to help you get started with Actions

name: Checking clean test compilation

on:
  push:
    paths:
      - "test"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: compile test cases
        run: 
          make -C test
        
